require("yanping.plugins") -- should be at the top
require("yanping.core.options")
require("yanping.core.keymaps")
require("yanping.core.colorscheme")
require("yanping.plugins.comment")
require("yanping.plugins.nvim-tree")
require("yanping.plugins.lualine")
require("yanping.plugins.telescope")
require("yanping.plugins.nvim-cmp")
require("yanping.plugins.lsp.mason")
-- require("yanping.plugins.lsp.lspsaga")
-- require("yanping.plugins.lsp.lspconfig")
-- require("yanping.plugins.lsp.null-ls")
-- require("yanping.plugins.autopairs")
-- require("yanping.plugins.treesitter")
-- require("yanping.plugins.gitsigns")
